name: Code Quality

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort mypy

      - name: Run Black
        run: black --check src/ tests/

      - name: Run Flake8
        run: flake8 src/ tests/

      - name: Run isort
        run: isort --check-only src/ tests/

      - name: Run mypy
        run: mypy src/
